apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: connections-ai
data:
  redis_url: "redis://redis:6379/0"
  ollama_url: "http://ollama:11434"
  puzzle_source_url: "https://raw.githubusercontent.com/Eyefyre/NYT-Connections-Answers/main/connections.json"
